#! /usr/bin/env python3

"""
Unit Testing quiteaproblem.py
"""

__author__ = "Ethan Ruiz"


import unittest
from quiteaproblem import answer

class TestGreetings(unittest.TestCase):
	def test1_answer(self):
		input1 = 'Problematic pair programming happens when pairing in pairs'
		self.assertEqual(answer(input1), 'yes')
	def test2_answer(self):
		input2 = 'the problem with the equation is where the answer lies within'
		self.assertEqual(answer(input2), 'yes')
	def test3_answer(self):
		input3 = 'probably I will think of a way to solve the question I have'
		self.assertEqual(answer(input3), "no")
	def test4_answer(self):
		input4 = 'hearing about problims make me think about other solutions'
		self.assertEqual(answer(input4), "no")


if __name__ == "__main__":
    unittest.main(verbosity=2)
